package mhs.src.logic;

import java.io.IOException;
import java.util.List;

import mhs.src.storage.Task;
import mhs.src.storage.TaskCategory;

public class CommandMark extends Command {

	Task lastTask;

	/**
	 * Default constructor for non index based commands
	 * 
	 * @param inputCommand
	 */
	public CommandMark(CommandInfo inputCommand) {
		List<Task> resultList;
		try {
			resultList = queryTaskByName(inputCommand);
			matchedTasks = resultList;
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	/**
	 * Constructor for index based commands
	 * 
	 * @param lastUsedList
	 */
	public CommandMark(List<Task> lastUsedList) {
		matchedTasks = lastUsedList;
	}

	/**
	 * Executes non index based commands
	 */
	public String executeCommand() {
		String outputString = new String();
		lastTask = new Task();
		if (matchedTasks.isEmpty()) {
			outputString = "No matching results found";
		}
		// if only 1 match is found then display it
		else if (matchedTasks.size() == 1) {
			// create task
			Task editedTask = matchedTasks.get(0);
			editedTask.setDone(true);
			try {
				lastTask = editedTask;
				dataHandler.update(editedTask);
				outputString = "Marked Task - '"
						+ matchedTasks.get(0).getTaskName() + "' as DONE";
				isUndoable = true;
			} catch (Exception e) {
				outputString = "Could not mark given task !";
			}
			isUndoable = true;
		}
		// if multiple matches are found display the list
		else {
			outputString = displayListOfTasksCategory(matchedTasks,
					TaskCategory.FLOATING);
			indexExpected = true;
		}
		return outputString;
	}

	/**
	 * Unmarks a task
	 */
	public String undo() {
		if (isUndoable()) {
			lastTask.setDone(false);
			try {
				dataHandler.update(lastTask);
				return MESSAGE_UNDO_CONFIRM;
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
				return MESSAGE_UNDO_FAIL;
			}
		} else {
			return MESSAGE_UNDO_FAIL;
		}
	}

	/**
	 * Executes based on only index. Uses last task list generated by previous
	 * mark command
	 */
	public String executeByIndex(int index) {
		String outputString = new String();
		if (indexExpected & index < matchedTasks.size()) {
			Task tempTask = matchedTasks.get(index);
			tempTask.setDone(true);
			lastTask = tempTask;
			try {
				dataHandler.update(tempTask);
				outputString = "Marked Task - '"
						+ matchedTasks.get(index).getTaskName() + "' as DONE";
				indexExpected = false;
				isUndoable = true;
			} catch (Exception e) {

			}
		} else {
			outputString = "Invalid Command";
		}
		return outputString;
	}

	/**
	 * Executes based on index and type. Uses last list generated.
	 */
	public String executeByIndexAndType(int index) {
		String outputString = new String();
		if (index < matchedTasks.size()) {
			Task tempTask = matchedTasks.get(index);
			tempTask.setDone(true);
			lastTask = tempTask;
			try {
				dataHandler.update(tempTask);
				outputString = "Marked Task - '"
						+ matchedTasks.get(index).getTaskName() + "' as DONE";
				isUndoable = true;
			} catch (Exception e) {

			}
		} else {
			outputString = "Invalid Command";
		}
		return outputString;
	}

}
